---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mywordpress
spec:
  selector:
    matchLabels:
      app: mywordpress
      product: mysql
  template:
    metadata:
      labels:
        app: mywordpress
        product: mysql
    spec:
      containers:
        - image: mysql
          name: mysql-container
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mywordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mywordpress
    product: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: mywordpress
spec:
  selector:
    matchLabels:
      app: mywordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mywordpress
        tier: frontend
    spec:
      containers:
        - image: jakubmichalko/mywp
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: rootpassword
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: mywordpress
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mywordpress
    tier: frontend
  type: NodePort
